### ISSUE TITLE
Consider splitting out the different interfaces

### ISSUE THREAD

**Issue by richierocks** [adamleerich/fancycut#2]
I'm a fan of having simple interfaces to functions, and since this is a small package, you can probably get away with splitting out the `intervals`/`buckets` usage from the `...` usage.

Maybe have

```r
fancychop <- function(x, ..., na.bucket = NA, unmatched.bucket = NA, out.as.factor = TRUE) {
  # parse the ...
  fancycut(x, intervals, buckets, na.bucket = na.bucket, 
    unmatched.bucket = unmatched.bucket, out.as.factor = out.as.factor)
}
```

and

```r
function(x, intervals, buckets = intervals, na.bucket = NA, 
    unmatched.bucket = NA, out.as.factor = TRUE) {
  # do the calculations
}
```

**Comment by richierocks** [comment]
BTW, `rlang` has some useful helper functions, for messing about with inputs, so you can do something like

```r
fancychop <- function(x, ..., unmatched) {
  dots <- list2(...)
  if(!is_dictionaryish(dots)) {
    stop("All arguments except x must have unique names.")
  }
  if(has_length(dots)) {
    buckets <- names2(dots)
    intervals <- as.character(dots)
  }
  fancycut(x, intervals, buckets, unmatched)
}
```

**Comment by adamleerich** [comment]
Thanks for this idea.  Just sticking with the "french fry" theme, I'm going to use the name `wafflecut`.

**Comment by adamleerich** [comment]
Richie, thanks for the referral to `rlang`, too.  I feel strongly that packages should try to not have dependencies unless they are really needed.  I will be using this in other projects, though!
