### ISSUE TITLE
parse_intervals() should accept trailing whitespace

### ISSUE THREAD

**Issue by richierocks** [adamleerich/fancycut#6]
Sorry, there's a tiny problem with the regular expression I gave you for matching an interval. It currently doesn't allow trailing whitespace.

This line: 

https://github.com/adamleerich/fancycut/blob/master/R/fancycut.R#L182

```r
rx <- "^\\s*(\\(|\\[)\\s*((?:[-+]?\\d*\\.?\\d+(?:[eE][-+]?\\d+)?)|(?:[-+]?Inf))\\s*,\\s*((?:[-+]?\\d*\\.?\\d+(?:[eE][-+]?\\d+)?)|(?:[-+]?Inf))\\s*(\\)|\\])$"
```

needs another `\\s*` before the final `$`.

```r
rx <- "^\\s*(\\(|\\[)\\s*((?:[-+]?\\d*\\.?\\d+(?:[eE][-+]?\\d+)?)|(?:[-+]?Inf))\\s*,\\s*((?:[-+]?\\d*\\.?\\d+(?:[eE][-+]?\\d+)?)|(?:[-+]?Inf))\\s*(\\)|\\])\\s*$"
```

**Comment by adamleerich** [comment]
Thanks for this catch.  You may have noticed that I took your regex and edited it quite a bit.  You can see where I put it together by piece in the file https://github.com/adamleerich/fancycut/blob/master/tests/testthat/test-interval-regex.R

I'll add that whitespace in and re-push.  I plan on pushing this up to CRAN later today or tomorrow.

Thanks!
